# Ensure that the latest version of Ubuntu 22.04 is running
FROM ubuntu:latest
# Update apt using apt-get update
RUN apt-get update
# Upgrade currently installed software through APT
RUN apt-get upgrade -y
# Install python3

# Install python3-pip

# Install flask